### ISSUE TITLE
Implementation violates Separation of Concerns

### ISSUE THREAD

**Issue by kevaundray** [crate-crypto/Ed448-Goldilocks#15]
To prevent overflow, the EC arithmetic contains specific details concerning the Field Arithmetic. See bias and weak_reduce.

This makes the EC arithmetic tightly coupled with the Field backend. 

There are two possible choices to make:

- Use a similar strategy to Curve25519 with radix 2^51

- Use saturated limbs for now 

(Maybe both?)

**Comment by CPerezz** [comment]
This will imply refactoring the whole module. 

I did that with zerocaf following curve25519 guidelines, so happy to work on that if helps!

**Comment by kevaundray** [comment]
Hey, 

Will push the offline code once I sort some bugs out, then add labels to issues as "help wanted". 

For the above solution, I believe you can do a full reduction after each operation, which will remove the bias and weak_reduce functions from the EC arithmetic layer.

**Comment by kevaundray** [comment]
Closing as the EC arithmetic, now reduces on each group operation
