### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by conradoplg** [crate-crypto/Ed448-Goldilocks#26]
We're using this crate in [FROST](https://github.com/ZcashFoundation/frost) and we want to publish our crates. However, we'll need a published version of this crate with the changes from #21 and #22.

Could you please publish a new version? ~Also please consider getting #25 merged first if you'd like, since that will make our code a bit cleaner~ ok that was fast :grin: 

I was digging around and found a bit confusing that the latest published crate is from the `develop` branch. I suggest merging that into `main` and getting the result published. But that's up to you, we'd be happy just to have a new release that contains the changes above. Thank you! :smile:

**Comment by kevaundray** [comment]
Hey,

Thanks for pointing out that there are two branches. I think we can deprecate `develop`.

I have published a 0.9 to crates.io please let me know if you have any issues :)

Thanks again for making the necessary changes!

**Comment by conradoplg** [comment]
Thank you very much for the quick response, it's working great! :tada:
